# Generated by Django 4.2.7 on 2023-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoderitems',
            name='invoice_no',
            field=models.CharField(default='invoice number', max_length=200),
        ),
    ]
