# Generated by Django 4.2.7 on 2023-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productvariant_image_varientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=10),
        ),
    ]
