# Generated by Django 4.2.7 on 2023-12-10 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productvariant_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='variant.jpg', upload_to='variant_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Variants',
            },
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='Images',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
        migrations.DeleteModel(
            name='varientImage',
        ),
        migrations.AddField(
            model_name='variantimages',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_images', to='store.productvariant'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product_images'),
        ),
    ]
