# Generated by Django 4.2.7 on 2023-12-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variantimages_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='old_price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorys', to='store.category'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.product'),
        ),
    ]
