# Generated by Django 4.2.7 on 2023-12-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_price_product_new_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='category',
        ),
    ]
