# Generated by Django 4.2.7 on 2023-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productvariant_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoderitems',
            options={'verbose_name_plural': 'Cart Order Items'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Cart Orders'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name_plural': 'Product variants'},
        ),
        migrations.AlterModelOptions(
            name='variantimages',
            options={'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='variantimages',
            old_name='variant',
            new_name='productvariant',
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='in_review', max_length=10),
        ),
    ]
