# Generated by Django 4.2.7 on 2023-12-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cartoderitems_options_alter_cartorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='brand.jpg', null=True, upload_to='brand'),
        ),
    ]
