# Generated by Django 4.2.7 on 2023-12-17 21:39

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_coupon_alter_address_user_redeemedcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.user_directory_path),
        ),
    ]
