# Generated by Django 4.2.7 on 2023-12-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
