# Generated by Django 4.2.7 on 2023-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
