# Generated by Django 4.2.7 on 2023-12-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_wishlist_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemedcoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='redeemedcoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='RedeemedCoupon',
        ),
    ]
