# Generated by Django 4.2.7 on 2024-01-02 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0033_remove_payment_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], default='HOME', max_length=10)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('address_line_1', models.CharField(default='Royal house', max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='kollam', max_length=50)),
                ('state', models.CharField(default='kerala', max_length=50)),
                ('postal_code', models.CharField(default='690522', max_length=10)),
                ('country', models.CharField(default='India', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default='Robin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
