# Generated by Django 4.2.7 on 2024-01-04 05:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0037_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction',
            new_name='WalletTransaction',
        ),
    ]
