# Generated by Django 4.2.7 on 2024-01-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_rename_transaction_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.FloatField(default=100),
        ),
    ]
