# Generated by Django 4.2.7 on 2024-01-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_wallettransaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerImage',
        ),
    ]
