# Generated by Django 4.2.7 on 2024-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_banner_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
    ]
