# Generated by Django 4.2.7 on 2024-01-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_bannerimage_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name_plural': 'Banner Images'},
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_images', to='store.banner'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='images',
            field=models.ImageField(default='banner.jpg', upload_to='banner_images'),
        ),
    ]
