# Generated by Django 4.2.7 on 2024-01-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_bannerimage_options_alter_bannerimage_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerImage',
        ),
    ]
