# Generated by Django 4.2.7 on 2024-01-08 08:29

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_banner_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='vid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
