# Generated by Django 4.2.7 on 2024-01-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_productvariant_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='vid',
            new_name='mid',
        ),
    ]
