# Generated by Django 4.2.7 on 2024-01-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_rename_vid_productvariant_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='mid',
        ),
    ]
