# Generated by Django 4.2.7 on 2023-12-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userform',
        ),
    ]
